In [5]:
import numpy as np

### `Array Creation 

Create a 1-dimensional array of integers from 1 to 10.

In [13]:
a=np.array([1,2,3,4,5,6,7,8,9,10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [7]:
array=np.arange(1,11)
print(array)

[ 1  2  3  4  5  6  7  8  9 10]


Create a 2-dimensional array with random float values of shape (3, 4).

In [14]:
array_2d=np.random.random((3,4))
print(array_2d)

[[0.98930171 0.61806428 0.90310387 0.41575744]
 [0.30904488 0.9630218  0.28071854 0.51410677]
 [0.67507003 0.26992686 0.66785742 0.01321284]]


Create a 3-dimensional array of zeros (2,3,4).

In [19]:
array_3d=np.zeros((2,3,4))
print(array_3d)

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]


### Array Operations

Given two 1-dimensional arrays, perform element-wise addition,subtraction, multiplication, and division.

In [20]:
a=np.array([1,2,3,4,5])
b=np.array([10,15,20,25,30])


In [22]:
sum=a+b
print(sum)

[11 17 23 29 35]


In [23]:
sum=np.add(a,b)
print(sum)

[11 17 23 29 35]


In [26]:
sub=b-a
print(sub)

[ 9 13 17 21 25]


In [27]:
mul=a*b
print(mul)

[ 10  30  60 100 150]


In [28]:
div=b/a
print(div)

[10.          7.5         6.66666667  6.25        6.        ]


Calculate the mean, median, and standard deviation of a given 1-
dimensional array.

In [29]:
a1=np.array([2,4,6,8,10,12,14,16,18,20])


In [31]:
mean=np.mean(a1)
print(mean)

11.0


In [32]:
median=np.median(a1)
print(median)

11.0


In [33]:
sd=np.std(a1)
print(sd)

5.744562646538029


Reshape a 1-dimensional array into a 2-dimensional array of shape (3,
4).

In [34]:
b1=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
c1=b1.reshape(3,4)
print(c1)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### Array Indexing and Slicing:

Extract the first row and last column of a 2-dimensional array.

In [37]:
first_row=c1[0,:]
print(first_row)

[1 2 3 4]


In [40]:
last_column=c1[:,-1]
print(last_column)

[ 4  8 12]


In [43]:
last_row=c1[2,:]
print(last_row)

[ 9 10 11 12]


Reverse the order of elements in a 1-dimensional array.

In [61]:
reversed_arr=np.flip(b1)
print("reversed array is :",reversed_arr)

reversed array is : [12 11 10  9  8  7  6  5  4  3  2  1]


In [45]:
reversed_array=b1[::-1]
print(reversed_array)

[12 11 10  9  8  7  6  5  4  3  2  1]



Select elements from a 2-dimensional array that satisfy a specific
condition (e.g., values greater than a certain threshold).

In [47]:
threshold=8
greater_value=c1>threshold
result=c1[greater_value]
print("Selected elements greater than", threshold, ":")
print(result)

Selected elements greater than 8 :
[ 9 10 11 12]


### Array Broadcasting:

Add a scalar value to each element of a 2-dimensional array.

In [49]:
scalar_value=15
added_value=c1+scalar_value
print("result after scalar value is added as :")
print(added_value)

result after scalar value is added as :
[[16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]]


Multiply a 1-dimensional array with a 2-dimensional array, leveraging
NumPy's broadcasting rules.

In [50]:
x=np.array([[1,2,3],[4,5,6]])
y=np.array([7,8,9])
z=x*y
print(z)

[[ 7 16 27]
 [28 40 54]]


### Linear Algebra:

Calculate the dot product of two 1-dimensional arrays.

In [52]:
x1= np.array([1, 2, 3])
y1=np.array([4,5,6])
z1=np.dot(x1,y1)
print("dot product is:")
print(z1)

dot product is:
32


Compute the matrix multiplication of two 2-dimensional arrays.

In [53]:
x1_2d= np.array([[1, 2],
                   [3, 4],
                   [5, 6]])

y1_2d=np.array([[7, 8, 9],
                   [10, 11, 12]])

z1_2d=np.dot(x1_2d,y1_2d)
print("matrix multiplication:")
print(z1_2d)

matrix multiplication:
[[ 27  30  33]
 [ 61  68  75]
 [ 95 106 117]]


Find the inverse and determinant of a square matrix.

In [58]:
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
matrix_inverse=np.linalg.inv(matrix)
print("inverse matrix is :")
print(matrix_inverse)

inverse matrix is :
[[ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]
 [-6.30503948e+15  1.26100790e+16 -6.30503948e+15]
 [ 3.15251974e+15 -6.30503948e+15  3.15251974e+15]]


In [62]:
matrix_determinant = np.linalg.det(matrix)
print("Determinant of the matrix:", matrix_determinant)

Determinant of the matrix: -9.51619735392994e-16
